name: Ruby

on:
  push:
    branches:
      - trunk

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.57.0
        override: true
    - name: Run the default task
      run: bundle exec rake
